[package]
name = "analyzer"
version = "0.1.0"
authors = ["Antoine <antoine.sb@orange.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "^0.5"
structopt = "^0.3"
lexer = "^0.1"
